spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:12000/study?useUnicode=true&characterEncoding=utf-8
    username: root
    password: mysecretpassword
  mail:
    host: smtp.qq.com
    username: 877369610@qq.com
    password: mcjpmnepxaodbdef
    port: 465
    properties:
      from: 877369610@qq.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  redis:
      host: 127.0.0.1
      port: 13000
  session:
    store-type: redis
    redis:
      namespace: test:spring:session